### ISSUE TITLE
Cannot build because of USERAUTH when running the helm goal in the fabric8 mvn plugin

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8-devops#242]
> [ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.82:helm (helm) on project artifactory: Execution helm of goal io.fabric8:fabric8-maven-plugin:2.2.82:helm failed: Failed to clone chart repo git@github.com:fabric8io/charts.git due: git@github.com:fabric8io/charts.git: USERAUTH fail -> [Help 1]

Stack looks like this:
http://pastebin.com/5xbwqbXV

Debugging shows that this is caused when using a private key which requires a passphrase to connect to git/github. 

PR on its way to fix this

**Comment by rhuss** [comment]
I still have this issue, however only when running `mvn clean install` in the top-level directory. When using `mvn install` it works, also `mvn package fabric8:helm`.

**Comment by christian-posta** [comment]
Does your private key for github.com require a password? Check the helm
docs real quick I added props you can use to pass in the password from the
CLI for your private key

http://fabric8.io/guide/mavenFabric8Helm.html

On Sunday, January 24, 2016, Roland Huß <notifications@github.com> wrote:

> I still have this issue, however only when running mvn clean install in
> the top-level directory. When using mvn install it works, also mvn
> package fabric8:helm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabric8io/fabric8-devops/issues/242#issuecomment-174278675>
> .
>


-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io

**Comment by rhuss** [comment]
Didn't try that yet but I wonder why I would need my private key when doing a local `mvn install` (without a `fabric8:helm-push`).

Btw, would be cool if an ssh-agent could be supported so that the private ssh password doesn't need to be exposed as a property (and because I dont remember which of the many ssh keys I use for github ;-)

Will go now looking for my github key ...
