### ISSUE TITLE
How to use only fabric8 chaosMonkey in k8s

### ISSUE THREAD

**Issue by cheyang** [fabric8io/fabric8-devops#291]
Hi ,
Is there any documentation about only running fabric8/chaosmonkey in k8s without other fabric8 service? And how to trigger chaos monkey? In restful API? 

I only found how to run it in fabric8. thanks

http://fabric8.io/guide/chaosMonkey.html

**Comment by cheyang** [comment]
Thanks, I've found the way to run it.

**Comment by davsclaus** [comment]
@cheyang you are welcome to share those details. Or maybe send a PR to update that documentation page.
