### ISSUE TITLE
Gogs not starting

### ISSUE THREAD

**Issue by tdcox** [fabric8io/fabric8-devops#328]
Using Gogs 0.6.1:

Gogs fails to start with the following:

2016/03/16 20:28:32 error: failed switching to "git": setgroups operation not permitted
2016-03-16 20:28:32,126 INFO exited: gogs (exit status 1; not expected)
2016-03-16 20:28:33,127 INFO gave up: gogs entered FATAL state, too many start retries too quickly
Bad protocol version identification 'GET / HTTP/1.1' from 172.17.0.1 port 38463

Looks like this could be similar to https://github.com/fabric8io/fabric8-devops/issues/327

**Comment by jimmidyson** [comment]
Fixed in #334. Requires gofabric8 >= 0.4.3 as well to configure SCC appropriately.

/cc @jstrachan

**Comment by jstrachan** [comment]
@jimmidyson awesome stuff many thanks!!
