### ISSUE TITLE
Jenkins Build pipeline is not available anymore

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-devops#50]
The Jenkins Build pipeline is not available anymore and in consequence we can't use anymore this real cool feature (https://github.com/cmoulliard/emea-partners-2015/blob/master/slideshow/images/jenkins-3.png) for demo / conference purpose.

**Comment by jstrachan** [comment]
new pipeline view is in the next release:
<img width="1305" alt="pipelines" src="https://cloud.githubusercontent.com/assets/30140/10303428/912dfbc8-6c0b-11e5-9840-c6d12bce29f3.png">

**Comment by rawlingsj** [comment]
looking good!!

**Comment by cmoulliard** [comment]
Whoowww. Very impressive.

**Comment by jstrachan** [comment]
I've just added the list of all pending pipelines to the environments page too; so from the Environments page you can watch all pending builds and see staging happen in real time across all the environments for a project:

<img width="1457" alt="environmentswithpendingpipelines" src="https://cloud.githubusercontent.com/assets/30140/10306072/5973ee5c-6c1c-11e5-839e-1c47fd86c1a1.png">
