### ISSUE TITLE
Not enough permission to create /app directory

### ISSUE THREAD

**Issue by KurtStam** [fabric8io/fabric8-devops#669]
I'm not sure as what user this is being executed but I'm seeing:

oc logs -f gogs-2-f659v 
mkdir: cannot create directory '/app/gogs/data/git': Permission denied
mkdir: cannot create directory '/app/gogs/data/ssh/': Permission denied
/opt/gogs/start.sh: line 24: cd: /app/gogs/data/ssh/: No such file or directory
panic: open gogs.rsa: permission denied

goroutine 1 [running]:
panic(0x519120, 0xc4200d3620)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/jdyson/go/src/github.com/fabric8io/docker-gogs/cmds/ssh-hostkeygen/ssh-hostkeygen.go:41 +0x2c1
2016/11/09 20:27:43 Creating admin user:  true
2016/11/09 20:27:43 [T] Custom path: /opt/gogs/custom
2016/11/09 20:27:43 [T] Log path: /app/gogs/data/logs
2016/11/09 20:27:43 [I] Gogs: Go Git Service 
2016/11/09 20:27:43 [.../gogs/models/repo.go:121 NewRepoContext()] [E] Fail to set git user.name(exit status 255): error: could not lock config file /app/gogs/data/.gitconfig: Permission denied

The /app directory does not exist.

--K

image: fabric8/gogs:v0.9.97

**Comment by KurtStam** [comment]
I'm pretty sure that directory created in the Dockerfile:
https://github.com/fabric8io/docker-gogs/blob/master/Dockerfile#L20

gets removed by the creation of the PV in that same place /app/gogs/data.

**Comment by KurtStam** [comment]
With this commit this bug should be fixed.

**Comment by KurtStam** [comment]
Seems like I was misguided and the problem is only solved by chmod 777 on the host-volumes. This is done on kubernetes by using pod.alpha.kubernetes.io/init-containers.
https://gist.github.com/rawlingsj/e15ba721d0fd30a6a3b68a42a38084af#file-gistfile1-txt-L83-L89

On Minishift it gets handled by gofabric8
https://github.com/fabric8io/gofabric8/blob/master/cmds/volumes.go#L194-L197

On other environments it needs to be done manually.

**Comment by wangxiang5050** [comment]
> 
> 
> Seems like I was misguided and the problem is only solved by chmod 777 on the host-volumes. This is done on kubernetes by using pod.alpha.kubernetes.io/init-containers.
> https://gist.github.com/rawlingsj/e15ba721d0fd30a6a3b68a42a38084af#file-gistfile1-txt-L83-L89
> 
> On Minishift it gets handled by gofabric8
> https://github.com/fabric8io/gofabric8/blob/master/cmds/volumes.go#L194-L197
> 
> On other environments it needs to be done manually.

I have the same problem, and sloved it, thanks!
