### ISSUE TITLE
Improve sonarqube usability

### ISSUE THREAD

**Issue by iocanel** [fabric8io/fabric8-devops#690]
There are two main usability problems:

i) Its extremely slow
ii) sonar scanner/runner seem to require access to the database.

The later may be possible to get overridden using configuration. But I think that it would be a good idea to switch to official images of sonarqube and mysql eitherway.

**Comment by rajdavies** [comment]
Fixed by https://github.com/fabric8io/fabric8-devops/commit/427bff0d9111e4573d6b65741f2039e24e65213b
