### ISSUE TITLE
Jenkins: load balancer check marks service unhealthy

### ISSUE THREAD

**Issue by mehiel** [fabric8io/fabric8-devops#697]
Environment:
- GCE as k8s provider
- Fabric8 installed using Helm
- exposer set to Ingress

The created health check in GCE targets `/blue`. But jenkins redirects (302) endpoints so that they contain an ending / (in this case `/blue/`) but LB doesn't follow redirects, marks service as unhealthy and returns 502.

After manually fixing the check path to contain the ending slash it works as expected, LB check is healthy and the service is exposed correctly.

As a totally newcomer in k8s and fabric8 I'm not sure if this is something I did wrong or something that comes from pod configuration and it could change (livenessProbe?).

**Comment by rawlingsj** [comment]
That's great, many thanks @mehiel - The fix will probably miss the next release but will be included in the following one.
